#pragma once

#define ICON_FONT_TRASH_CAN u8"\ufa78"
#define ICON_FONT_PLUS u8"\uf415"
#define ICON_FONT_MINUS u8"\uf374"

#define BUTTON_LABEL_RESET ICON_FONT_TRASH_CAN
#define BUTTON_LABEL_PLUS ICON_FONT_PLUS
#define BUTTON_LABEL_MINUS ICON_FONT_MINUS
